_wandb:
    value:
        cli_version: 0.21.0
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 80
            "4": 3.8.10
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
